[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun install && bun run db:generate && bun run db:push && SKIP_ENV_VALIDATION=true bun run build"
  publish = ".next"

  # Build timeout and resources
  [build.processing]
    timeout = "20m"

  [build.environment]
    NODE_VERSION = "18"
    NODE_ENV = "production"
    SKIP_ENV_VALIDATION = "true"
    # Database will be handled via environment variables
    # JWT secrets will be set via Netlify environment variables

[functions]
  # Configure serverless functions
  directory = ".netlify/functions"
  node_bundler = "esbuild"

  # API routes timeout
  [functions.api]
    timeout = 30

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), location=(), payment=()"

    # Content Security Policy
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'unsafe-inline' https://va.vercel-scripts.com https://vitals.vercel-analytics.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' https://vitals.vercel-analytics.com https://api.openai.com;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self';
    '''

    # HSTS
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# API routes headers
[[headers]]
  for = "/api/*"
  [headers.values]
    # API-specific headers
    Cache-Control = "no-store, no-cache, must-revalidate, private"
    X-Robots-Tag = "noindex, nofollow"

    # CORS headers (will be overridden by middleware for specific routes)
    Access-Control-Allow-Origin = "https://techflow-datavault.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"

# Static assets caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image optimization
[images]
  remote_images = [
    "https://source.unsplash.com/.*",
    "https://images.unsplash.com/.*",
    "https://ext.same-assets.com/.*",
    "https://ugc.same-assets.com/.*"
  ]

# Redirects and rewrites
[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/api/v1/*"
  to = "/api/:splat"
  status = 301

# Error pages
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Prerendered routes for better performance
[[plugins]]
  package = "@netlify/plugin-nextjs"

  [plugins.inputs]
    # Skip edge middleware for some routes to improve performance
    experimental = { "skipMiddlewareUrlNormalize" = true }

# Environment-specific configurations
[context.production]
  [context.production.environment]
    NODE_ENV = "production"
    NEXT_TELEMETRY_DISABLED = "1"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "staging"
    NEXT_TELEMETRY_DISABLED = "1"

[context.branch-deploy]
  [context.branch-deploy.environment]
    NODE_ENV = "development"

# Form handling (if needed)
[forms]
  settings = { }

# Large Media (for large files)
[lfs]
  enabled = false

# Split testing (A/B testing)
[split-testing]
  enabled = false
